### ISSUE TITLE
[Tooling] the flow runner loses previous input when runtime reconnects

### ISSUE THREAD

**Issue by pavelgj** [firebase/genkit#1324]

**Comment by tonybaroneee** [comment]
This is because we hard-refresh the page currently on actions reload. We're looking into a solution to not have to do that, but I bet monaco might still re-render once the actions array is hot-swapped back in, so input would still be lost anyways.

I think the broader solution here is leveraging localStorage to remember flow input + auth JSON (Denis in discord wanted something similar for flow auth to not have to keep re-inputting it on refresh).

**Comment by MichaelDoyle** [comment]
Should this be combined with #1310?

**Comment by MichaelDoyle** [comment]
See also: https://discord.com/channels/1255578482214305893/1306933277189341184

**Comment by tonybaroneee** [comment]
We decided to just prevent auto-refresh when viewing a runner page, and instead adjust the runtime banner to show that it has been reconnected and offer a button to refresh the page. Show this state until the page is refreshed, or the runtime is disconnected again.

**Comment by tonybaroneee** [comment]
Fixed with https://github.com/FirebasePrivate/genkit-ui/pull/1206.
