### ISSUE TITLE
Update to use the platform standard model name / version in samples and snippets and imports (for Google AI and Vertex AI)

### ISSUE THREAD

**Issue by rachelsaunders** [firebase/genkit#460]
For both Google AI and Vertex AI, we try to use the most capable and developer-friendly model as possible in our samples, snippets, etc.

The Gemini 1.5 models can understand both text-only and multimodal (even in chat) inputs, which relieves the developer from switching b/w Gemini 1.0 Pro and Gemini 1.0 Pro Vision.  For both platforms, there's also a stable version of each Gemini 1.5 model available.

For the foreseeable future, we have the guidance of using Gemini 1.5 Flash for all samples and snippets... unless the feature/capability isn't supported on Gemini 1.5 Flash.  In those cases, use Gemini 1.5 Pro (which supports more features, but has a lower RPM).

This is the guidance for the explicit model names in code:

- For Google AI: use `gemini-1.5-flash` (or `gemini-1.5-pro` when required)
- For Vertex AI: use `gemini-1.5-flash-001` (or `gemini-1.5-pro-001` when required)

**Comment by kevinthecheung** [comment]
I have addressed this to the extent that in the docs, Gemini 1.5 Flash is the canonical model example, and Gemini 1.5 Pro is the canonical example of a model that is not Flash.

I have not used the names of specific versions (`gemini-1.5-flash-001`) because I believe that would circumvent the nice defaults provided by Genkit.
