### ISSUE TITLE
[Go] ollama plugin needs live tests

### ISSUE THREAD

**Issue by jba** [firebase/genkit#609]
go/plugins/ollama has no tests against actual models to demonstrate that the code works.

**Comment by eddumelendez** [comment]
Hi, may I suggest to use [Testcontainers for Go's Ollama Module](https://golang.testcontainers.org/modules/ollama/)

**Comment by cabljac** [comment]
We could also use ovai, which seems to wrap Vertex AI with an API interface of Ollama?

**Comment by cabljac** [comment]
@eddumelendez I implemented it with Testcontainers, but we're limited in that we can't use Docker. The solution instead is just to assume the dev has an ollama instance running, and put the test behind a flag (see PR) :)

**Comment by eddumelendez** [comment]
HI @cabljac, I think you meant Docker Desktop, right? However, you can use Docker at GitHub workflows without any issues.

**Comment by cabljac** [comment]
@eddumelendez I'm not sure to be honest, just reiterating what I was told, check out the PR for what Pavel said if interested :)

**Comment by mdelapenya** [comment]
Hey @cabljac, testcontainers-go maintainer here 👋 

You don't need Docker Desktop to be installed in your local machines to use testcontainers-go, just a container runtime that is 100% compatible with the Docker engine APIs. If podman or colima or any other satisfy that, then they should work out-of-the-box.

That's what @eddumelendez mentioned about the GH actions: they come with the Docker engine (moby/moby) already installed so your GH workflows will benefit from using testcontainers approach in a transparent manner. For local experience in developers laptop, just having a docker engine running is enough: for Linux users it's fairly simple to install Docker. For MacOS and Windows, you could try the aforementioned container runtimes and you could also give it a try to [testcontainers desktop](https://testcontainers.com/desktop/) alternative (it's a free app).

The benefits of using the testcontainers approach is that you don't need to share knowledge through a README, or a shell script or a makefile to start the runtime/test-time dependencies of your project. Because everything is in code, you just clone and run your tests. I saw you started with testcontainers-go first, so I'm sure you see the value on this. Please let me know if you need anything else from our side; from OSS project to OSS project, we'd like to support you in the most friendly manner 😊
