### ISSUE TITLE
I have created a dynamic Ollama plugin please can you accept the PR

### ISSUE THREAD

**Issue by AshleyTuring** [firebase/genkit#775]
**Is your feature request related to a problem? Please describe.**
See https://github.com/firebase/genkit/pull/774

**Describe the solution you'd like**
See https://github.com/firebase/genkit/pull/774
please merge or provide further instructions. Note I have accepted the contributor terms, however, it is not reflecting for some reason.

**Describe alternatives you've considered**
See https://github.com/firebase/genkit/pull/774

**Comment by MichaelDoyle** [comment]
Hey Ashley! Thanks for all your efforts here. We are not accepting 3P plugins into the main repository at this time. We encourage you to publish to `genkitx-` on NPM, just as you've already done, so that folks can easily find your plugin. If you don't want to be in the business of maintaining the repository itself, you could consider collaborating with other members of the community to share the load. As of today, the biggest collection of plugins is currently maintained by TheFireCo: https://github.com/TheFireCo/genkit-plugins.

Thanks,
Mike
